### ISSUE TITLE
Request improvement

### ISSUE THREAD

**Issue by choisangh** [white07S/TradingPatternScanner#2]
hello
I'm interested this project because it's similar to my work in the company.
your project is cool but, i want some improvement

1. chart pattern start point and end point : It's unclear when the charts start and end.
2. detail : each point to be clear which part of the chart pattern.

my project uses argrelextrema function in scipy to recognize zigzag patterns.
next Explore patterns using different conditional expressions in zigzag pattern.
call me if you're interested. I want to join you in your project to share opinion.
![image](https://user-images.githubusercontent.com/92343445/217745187-f542658b-c728-409d-b927-aa22abf539a3.png)

**Comment by choisangh** [comment]
@white07S

**Comment by white07S** [comment]
Let's discuss over [LinkedIn](https://www.linkedin.com/in/preetam-sharma-80350a194).
