### ISSUE TITLE
The signal seems to be too sensitive

### ISSUE THREAD

**Issue by idsilent** [white07S/TradingPatternScanner#3]
I tried the codebase and there are so many signals that are not obvious
But still feel that this codebase is too useful, really looking forward to the subsequent code

**Comment by white07S** [comment]
I am working on proper signal processing rather than conditional and masking based detection, there will be some update soon.

**Comment by idsilent** [comment]
Great! Looking forward to the subsequent updates.

**Comment by white07S** [comment]
Recently added few extra methods to solve the issue of sensitivity and it should be good to go if you pick the right algorithm based on situation and instrument.
